doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        App\Shared\infrastructure\Database\Migrations: '%kernel.project_dir%/Shared/Infrastructure/Database/Migrations'
    enable_profiler: false
